# Generated by Django 5.0.4 on 2024-05-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cityairquality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('air_quality', models.CharField(max_length=100)),
                ('air_quality_index', models.IntegerField()),
            ],
            options={
                'db_table': 'cityairquality',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='100', max_length=100),
        ),
        migrations.AlterModelTable(
            name='user',
            table='signup',
        ),
    ]
